lgbm_hyperspace = {'num_leaves': [150, 200, 250],
              'min_child_samples': [50, 75, 100],
                'min_data_in_leaf': [50, 100, 200],
                'objective': ['regression_l2', 'huber'],
                'max_depth': [5, 10, 15, 20],
                'learning_rate': [0.01, 0.005],
                "boosting_type": ["gbdt"],
                "subsample_freq": [1],
                "subsample": [0.5, 0.9],
                "bagging_seed": [11],
                "metric": ['mae'],
                "verbosity": [-1],
                'reg_alpha': [0.1, 0.5, 1.0],
                'reg_lambda': [0.1, 0.5, 1.0],
                'colsample_bytree': [0.5, 0.9]
         }

catboost_hyperspace = {'iterations': [100000], 
          'learning_rate': [0.02],
          'border_count': [254],
          'task_type': ['GPU'],
          'depth': [8],
          'bagging_temperature': [1.0],
          'random_strength': [1.5],
          'l2_leaf_reg': [2.5],
          'min_data_in_leaf': [1],
          'one_hot_max_size': [64],
          #'rsm': [0.8],
          #'leaf_estimation_backtracking': ['Armijo'],
          'grow_policy': ['SymmetricTree']}
